services:
  - type: web
    name: transitops
    runtime: docker
    plan: free
    healthCheckPath: /web/health
    dockerCommand: /bin/sh -c "odoo -d transitops -i base --stop-after-init --no-http && odoo"
    envVars:
      - key: HOST
        fromDatabase:
          name: transitops-db
          property: host
      - key: PORT
        fromDatabase:
          name: transitops-db
          property: port
      - key: USER
        fromDatabase:
          name: transitops-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: transitops-db
          property: password
      - key: DB_NAME
        value: transitops
      - key: ODOO_ADMIN_PASSWD
        generateValue: true

databases:
  - name: transitops-db
    plan: free
