services:
  - type: web
    name: transitops
    runtime: docker
    plan: free
    healthCheckPath: /web/health
    envVars:
      - key: HOST
        fromDatabase:
          name: transitops-db
          property: host
      - key: PORT
        fromDatabase:
          name: transitops-db
          property: port
      - key: USER
        fromDatabase:
          name: transitops-db
          property: user
      - key: PASSWORD
        fromDatabase:
          name: transitops-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: transitops-db
          property: database
      - key: ODOO_ADMIN_PASSWD
        generateValue: true
      - key: DISABLE_DBFILTER
        value: "1"

databases:
  - name: transitops-db
    plan: free
